CREATE TABLE cred_suc (
    NRO_CAJ_SF		CHAR( 5) NOT NULL,
    DIR_VTA		CHAR(20) NOT NULL,
    CAJ_FIC		CHAR( 5) NOT NULL,
    CAJ_DEV		CHAR( 5) NOT NULL,
    DESCRIP		CHAR(30) NOT NULL,
    STATUS		CHAR( 1) NOT NULL )


