make -f makeLinux AnulDaemon
make -f makeLinux CACStat
make -f makeLinux CACStatus
make -f makeLinux CfgX25
make -f makeLinux CierreLoteCA
make -f makeLinux CierreLoteCASuc
make -f makeLinux Config
make -f makeLinux Daemon
make -f makeLinux EventQueue
make -f makeLinux IniX25
make -f makeLinux LinkX25
make -f makeLinux Log
make -f makeLinux PidTable
make -f makeLinux Pos
make -f makeLinux QChild
make -f makeLinux Queues
make -f makeLinux Semaphores
make -f makeLinux SendAnul
make -f makeLinux SendPing
make -f makeLinux SendRev
make -f makeLinux Sockets
make -f makeLinux Status
make -f makeLinux TCPDaemon
make -f makeLinux TimeOutDaemon
make -f makeLinux TimeOutQueue
make -f makeLinux TraceNmbr
make -f makeLinux TrxHeap
make -f makeLinux X25Daemon
